language: node_js
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- echo {\"token\":\"$TSDRC_TOKEN\"} > .tsdrc
- tsd reinstall --save --overwrite
before_install:
- rm npm-shrinkwrap.json
- export CHROME_BIN=chromium-browser
- npm install -g bower tsd tslint grunt
- gem install bundler
- bundle install
cache:
  bundler: true
  directories:
    #- node_modules
    #  - "$(npm config get prefix)/bin/bower"
    #- "$(npm config get prefix)/bin/tsd"
    #- "$(npm config get prefix)/bin/tslint"
    #- "$(npm config get prefix)/bin/grunt"
env:
  global:
  - CXX=g++-4.8
  - secure: cjNllfK1HZ+XPGZD6I20EhISIeD7IFh2fFRow4m9DHVSeaa0rkPTuxZu9J08hOw28ze1CM2tSIqBEeDEYqN49GaV38u/LkfHisw+ToK0HO+iad8sRqm4zuhxMHjJbV5viAuCTKVBFL+iL5doPec5tgtkEEumS3MCW9NGgxVqYRE0YQUT67p8hKMwFSdRxNi1dI4mrwB4fM3rTkirVnFfGPrfQX18iBtZhb0/5NdT4Fbw/mfqSD2ON8yxWLHku1gMeP2UltUum3JPlOw39VrmfpTpkVTREH9A2Yark/09/4VVub4A/al0dw2s4AkCrWyImHeDTubdgZGeaFLx8DngbcCMiAGoKEQX/nXKLhzwItbVLWDnk1bblmliaN9NK7Z0dHA2wbYCr0F8OEDDjeb7OUgU77OES7Fcq/Nfw2SR95EmUSVCl4iqHuANo2Ej4ip8nLnv27+5jBYXGUR16O+jrHDoX4khl5czBjWEpBA5sTYF3gY5PjUogMDfihbBJqg+Jxa4W3Dst2UqATQ+X+kjLVZ8mueeYLcDc5gkx7ueSZsudDx8jW5dEL+7ZLQypXSEE50y1cXjdalVT5OVFnyvBRdp6G/wLTga+CXhcfranbRWv1XUZ8HQZoasI4Bxr/ksoIVHiLWKceIaSN2YvDaVNxAWoKszNnE52XYmY7XU/38=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
